[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://raas-backend.onrender.com/api"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://raas-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://raas-backend.onrender.com/api"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://raas-backend-dev.onrender.com/api"

[context.branch-deploy.environment]
  NEXT_PUBLIC_API_URL = "https://raas-backend-dev.onrender.com/api"